package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_10;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/10] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"JSON"},{module=>"PSGI"},{module=>"Plack"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 10)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/10> (retrieved on 2016-11-18). Visit the URL for the full contents.

