package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_02;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/2] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Amon2"},{module=>"App::Cmd"},{module=>"Dancer"},{module=>"Dancer2"},{module=>"HTTP::Server::PSGI"},{module=>"Moo"},{module=>"Moose"},{module=>"Plack"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 2)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 2)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/2> (retrieved on 2016-11-18). Visit the URL for the full contents.

