package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/7] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"File::Spec"},{module=>"HTTP::Tiny"},{module=>"JSON"},{module=>"Template"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 7)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 7)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/7> (retrieved on 2016-11-18). Visit the URL for the full contents.

