package Acme::CPANLists::Import::PerlDancerAdvent::2014;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"DBIx::Class"},{module=>"Dancer"},{module=>"Dancer2"},{module=>"Amon2"},{module=>"App::Cmd"},{module=>"HTTP::Server::PSGI"},{module=>"Moo"},{module=>"Moose"},{module=>"Plack"},{module=>"Carton"},{module=>"HTTP::Server::Simple"},{module=>"Pinto"},{module=>"Plack::Builder"},{module=>"local::lib"},{module=>"App::FatPacker"},{module=>"MIME::Types"},{module=>"PSGI"},{module=>"Dancer2::Handler::AutoPage"},{module=>"Dancer2::Handler::File"},{module=>"Plack::Middleware::Static"},{module=>"File::Spec"},{module=>"HTTP::Tiny"},{module=>"JSON"},{module=>"Template"},{module=>"Dancer2::Core::App"},{module=>"Dancer2::Core::Dispatcher"},{module=>"Plack::App::URLMap"},{module=>"Dancer2::Serializer::CBOR"},{module=>"Dancer2::Test"},{module=>"Dancer::Test"},{module=>"HTTP::Cookies"},{module=>"HTTP::Request"},{module=>"HTTP::Response"},{module=>"LWP"},{module=>"LWP::Protocol::PSGI"},{module=>"LWP::UserAgent"},{module=>"Plack::Test"},{module=>"Test::More"},{module=>"Test::WWW::Mechanize"},{module=>"Test::WWW::Mechanize::PSGI"},{module=>"WWW::Mechanize"},{module=>"Dancer2::Core::Factory"},{module=>"Dancer2::Plugin"},{module=>"Dancer2::Plugin::Auth::Tiny"},{module=>"Dancer2::Plugin::Database"},{module=>"Dancer2::Plugin::Auth::Extensible"},{module=>"Dancer2::Plugin::Passphrase"},{module=>"Digest"},{module=>"Plack::Middleware"},{module=>"Plack::Middleware::ContentLength"},{module=>"Plack::Middleware::FixMissingBodyInRedirect"},{module=>"Plack::Middleware::Head"},{module=>"Plack::Middleware::RemoveRedundantBody"},{module=>"Plack::Util"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/> (retrieved on 2016-11-18). Visit the URL for the full contents.

