package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_06;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/6] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"Dancer2::Handler::AutoPage"},{module=>"Dancer2::Handler::File"},{module=>"Plack"},{module=>"Plack::Middleware::Static"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 6)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 6)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/6> (retrieved on 2016-11-18). Visit the URL for the full contents.

