package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/19] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2::Plugin::Auth::Extensible"},{module=>"Dancer2::Plugin::Auth::Tiny"},{module=>"Dancer2::Plugin::Passphrase"},{module=>"Digest"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 19)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/19> (retrieved on 2016-11-18). Visit the URL for the full contents.

