package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_04;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/4] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Carton"},{module=>"Dancer2"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 4)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 4)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/4> (retrieved on 2016-11-18). Visit the URL for the full contents.

