package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_21;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/21] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"PSGI"},{module=>"Plack::Middleware::ContentLength"},{module=>"Plack::Middleware::FixMissingBodyInRedirect"},{module=>"Plack::Middleware::Head"},{module=>"Plack::Middleware::RemoveRedundantBody"},{module=>"Plack::Middleware::Static"},{module=>"Plack::Util"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 21)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 21)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/21> (retrieved on 2016-11-18). Visit the URL for the full contents.

