package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/9] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"Dancer2::Core::App"},{module=>"Dancer2::Core::Dispatcher"},{module=>"Plack::App::URLMap"},{module=>"Plack::Builder"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 9)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 9)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/9> (retrieved on 2016-11-18). Visit the URL for the full contents.

