package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_12;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/12] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Dancer2"},{module=>"Dancer2::Test"},{module=>"Dancer::Test"},{module=>"HTTP::Cookies"},{module=>"HTTP::Request"},{module=>"HTTP::Response"},{module=>"JSON"},{module=>"LWP"},{module=>"LWP::Protocol::PSGI"},{module=>"LWP::UserAgent"},{module=>"PSGI"},{module=>"Plack"},{module=>"Plack::Test"},{module=>"Test::More"},{module=>"Test::WWW::Mechanize"},{module=>"Test::WWW::Mechanize::PSGI"},{module=>"WWW::Mechanize"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 12)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 12)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/12> (retrieved on 2016-11-18). Visit the URL for the full contents.

