package Acme::CPANLists::Import::PerlDancerAdvent::2014_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2014/3] (retrieved on 2016-11-18). Visit the URL for the full contents.",entries=>[{module=>"Carton"},{module=>"Dancer2"},{module=>"HTTP::Server::PSGI"},{module=>"HTTP::Server::Simple"},{module=>"Pinto"},{module=>"Plack"},{module=>"Plack::Builder"},{module=>"local::lib"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2014 (day 3)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2014 (day 3)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2014/3> (retrieved on 2016-11-18). Visit the URL for the full contents.

